name: hangman
description: Hangman Game
publish_to: "none" # Remove this line if you ever intend to publish to pub.dev (not needed for Play Store only)

version: 1.2.0+7  # <<< THIS LINE HAS BEEN UPDATED

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rflutter_alert: ^2.0.7
  material_design_icons_flutter: ^7.0.7296
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_spinkit: ^5.2.0
  date_format: ^2.0.7
  google_mobile_ads: ^6.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  in_app_purchase: ^3.2.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/hangman_words.txt

  fonts:
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23